// Document variables
:VERSION: 5.0
= SymetryML {VERSION}: Onboarding Guide
:toc:
:source-highlighter: rouge
:toclevels: 2
:toc-placement: preamble
:doctype: book

Copyright © 2020 by Symetry, Inc. +
14 Pine Street, Ste 6 +
Morristown, NJ 07960 +
All Rights Reserved +
March 31st, 2020

[[introduction]]
== Introduction

Welcome to SymetryML. The intent of this document is to help the user get up and running with SymetryML. This document will go over the minimum technical requirements, data sources and file formats that are compatible with SymetryML, as well as  directing the user to more detailed tutorials regarding installation, application, and maintenance of SymetryML.   


[[platforms]]
== SymetryML Platform Options


[[aws-cloud-technical-requirement-for-symetryml]]
=== Cloud: Amazon Web Services (AWS)

The following table lists all the instance types which SymetryML can be deployed on. For up to date pricing information regarding cost of the various instance types in conjunction with the licensing fees of SymetryML, visit the SymetryML solution on the AWS Marketplace. 

.AWS Instance Types
[cols="5,5,5,5,5",options="header",]
|=========================================================
| Model | vCPU | Memory | GPU | GPU Memory 
| c5.4xLarge | 16 | 32 | 0 | 0
| c5.9xLarge | 36 | 72 | 0 | 0
| c5.18xLarge | 72 | 144 | 0 | 0
| p3.8xlarge | 32 | 244 | 4 | 64
| p3.16xlarge | 64 |488 | 8 | 128 
|=========================================================



[[technical-requirements]]
=== On Premise: Technical Requirements

Please consult <<SML_Tech_Requirements.adoc#, SML Tech Requirements>> for details

[[user-interface]]
== User Interface

=== Rest Application Programming Interface (API)
To access SymetryML via Rest API, please consult 
<<../documentations/rest/SML_REST_API_Reference_Guide.adoc#, SML Rest API Reference Guide>> for details.

The <<../documentations/rest/SML_REST_API_Reference_Guide.adoc#, SML Rest API Reference Guide>> describes the SymetryML REST API. The API lets you create, update, and delete
SymetryML projects that can be used for data-mining exploration and predictive modelling.

This reference manual is intended for software developers who write client applications that interact with the SymetryML REST API.


=== Graphical User Interface (GUI)
To access SymetryML via the GUI, please consult 
<<../documentations/web/SML_Web_User_Guide.adoc#, SML Web User Guide>> for details.

The <<../documentations/web/SML_Web_User_Guide.adoc#, SML Web User Guide>> will give a general overview of SymetryML, including a brief introduction to data-mining and applying its concepts to SymetryML workflow. The core intention of this guide is to provide readers with a brief summary of the information needed to implement SymetryML successfully into their data-driven projects and to cover typical usage scenarios.


== Data Source Connections

=== SymetryML Remote Data Source Connections

SymetryML can connect to the following remote data sources:

* AWS Redshift
* AWS S3
* HTTP/HTTPS
* JDBC
* SFTP
* Spark
* Splunk
* Kafka
* New data sources can be accommodated with SymetryML's data source plugin interface.


[[file-formats]]
== File formats

[[symetryml-supported-file-formats]]
=== SymetryML supported file formats

* CSV - Comma Seperated Value

New file formats can be accommodated with SymetryML's datsource plugin interface.

== Integrations

=== Data Visualization Integrations
==== SymetryML integration with Tableau

Whether accessing SymetryML via the Rest API or the GUI, SymetryML integrates seamlessly with Tableau via the AWS cloud environment to support and push output to desired Dashboards, Reporting and Key Performance Inidcators (KPI's).  


[[reference-documents]]
== Reference Documents

[[symetryml-tutorials]]
=== SymetryML Tutorials / Example

The following is a list of SymetryML resources which the user can access for more detailed information regarding the installation, application, and maintenance of SymetryML.  

[[symetryml-installation-guide]]
==== SymetryML Installation Guide
The <<SML_Installation_Guide.adoc#, Symetry Installation Guide>> will guide you through the install, upgrade and configuration of the SymetryML suite of applications.


[[symetryml-examples]]
==== SymetryML Examples

This section guides you to tutorials with sample code demonstrating how to build SymetryML projects in different environments with Python and Scala.

*_Python examples_* +

Using a <<../examples/Python/pyspark/iris-local-example-pyspark.py#, Spark context>> to host a symetry project and learn a local data file. +

Using <<../examples/Python/pyspark/iris-s3-example-pyspark.py#, Spark>> to perform a distributed learn on an S3 datasource. +


*_Python notebook examples_* +
 <<../examples/Python/notebook/README.md#, ReadMe document>> +
 
Hidden Markov Model <<../examples/Python/notebook/SML-PartOfSpeech-Tagger-HMM-Tutorial.ipynb#, Part of Speech Tagger>> tutorial. +

Using a local spark cluster to perform a distributed learn on an S3 datasource in a <<../examples/Python/notebook/amazon-s3-example-pyspark.ipynb#, notebook>> +

Using an external spark cluster to perform distributed learn on an S3 datasource in a <<../examples/notebook/amazon_s3_Example.ipynb#, notebook>> +

Using Py4J to learn a local data file in a <<../examples/Python/notebook/local-example-py4j.ipynb#, notebook>> +

[[symetryml-admin-users-guide]]
==== SymetryML Admin Users Guide. TBD <<<=== DO WE NEED THIS
The SymetryML Admin CLI is a command-line application that allows administrators to manage
service updates and user credentials. This user guide describes the common usage patterns for the
SymetryML Admin CLI.

[[maintenance-and-support]]
=== Maintenance and Support Guide

The guide gives direction on how to access technical support, as well as giving guidance on the topics of software maintenance and software upgrades. 
